import { useState } from "react";
import api from "../../../config/api";
import { C } from "./constants";
import { Modal, Btn, Alert } from "./primitives";

export const GenerateInvoicesModal = ({ group, onClose }) => {
  const [status,   setStatus]   = useState("idle"); // idle | loading | done | error
  const [result,   setResult]   = useState(null);
  const [errorMsg, setErrorMsg] = useState(null);

  const handleGenerate = async () => {
    setStatus("loading");
    try {
      const res = await api.post("/fees/invoices/generate", {
        term_id:  group.term_id,
        class_id: group.class_id,
      });
      setResult(res.data?.data);
      setStatus("done");
    } catch (err) {
      setErrorMsg(err.response?.data?.message || "Failed to generate invoices.");
      setStatus("error");
    }
  };

  const handlePrint = () => {
    const win  = window.open("", "_blank");
    const rows = group.rows.map(r => `
      <tr>
        <td style="padding:10px 16px;border-bottom:1px solid #eee">${r.fee_type}</td>
        <td style="padding:10px 16px;border-bottom:1px solid #eee;text-align:right">
          ${!r.is_mandatory ? '<span style="font-size:11px;color:#D97706;border:1px solid #D9770640;border-radius:10px;padding:1px 7px;margin-right:6px">Optional</span>' : ""}
          KES ${parseFloat(r.amount).toLocaleString("en-KE")}
        </td>
      </tr>`).join("");
    const total = group.rows.reduce((s, r) => s + parseFloat(r.amount || 0), 0);

    win.document.write(`
      <!DOCTYPE html><html><head>
        <title>Fee Structure — ${group.class_name || `Class ${group.class_id}`}</title>
        <style>
          body{font-family:'Segoe UI',sans-serif;padding:40px;color:#0F172A;}
          h1{font-size:22px;margin-bottom:4px;}
          .sub{color:#64748B;font-size:13px;margin-bottom:28px;}
          table{width:100%;border-collapse:collapse;}
          th{background:#F8FAFC;padding:10px 16px;text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:.6px;color:#94A3B8;border-bottom:2px solid #E4E8EF;}
          .total-row td{font-weight:700;font-size:15px;border-top:2px solid #E4E8EF;padding:14px 16px;}
          @media print{button{display:none;}}
        </style>
      </head><body>
        <h1>${group.class_name || `Class ${group.class_id}`} — Fee Structure</h1>
        <div class="sub">${group.term_name || `Term ${group.term_id}`} &nbsp;·&nbsp; Academic Year ${new Date().getFullYear()}</div>
        <table>
          <thead><tr><th>Description</th><th style="text-align:right">Amount</th></tr></thead>
          <tbody>
            ${rows}
            <tr class="total-row">
              <td>Total</td>
              <td style="text-align:right">KES ${total.toLocaleString("en-KE")}</td>
            </tr>
          </tbody>
        </table>
        <div style="margin-top:40px;font-size:11px;color:#94A3B8">
          Generated by Msingi School Management System · ${new Date().toLocaleDateString("en-KE")}
        </div>
        <br/>
        <button onclick="window.print()" style="padding:10px 24px;background:#4F46E5;color:#fff;border:none;border-radius:8px;cursor:pointer;font-size:14px">
          🖨 Print / Save as PDF
        </button>
      </body></html>
    `);
    win.document.close();
  };

  return (
    <Modal
      title="Generate Invoices"
      subtitle={`${group.class_name || `Class ${group.class_id}`} · ${group.term_name || `Term ${group.term_id}`}`}
      onClose={onClose} width={520}
    >
      <div style={{ display: "flex", flexDirection: "column", gap: 18 }}>

        {/* Fee breakdown */}
        <div style={{ background: C.bg, borderRadius: 12, padding: 16, border: `1px solid ${C.border}` }}>
          <div style={{ fontSize: 11, fontWeight: 600, color: C.muted, textTransform: "uppercase", letterSpacing: .5, marginBottom: 12 }}>Fee Breakdown</div>
          {group.rows.map((r, i) => (
            <div key={i} style={{ display: "flex", justifyContent: "space-between", padding: "7px 0", borderBottom: i < group.rows.length - 1 ? `1px solid ${C.border}` : "none", fontSize: 13 }}>
              <span>
                {r.fee_type}{" "}
                {!r.is_mandatory && <span style={{ fontSize: 10, color: C.amber }}>Optional</span>}
              </span>
              <span style={{ fontFamily: "'DM Mono', monospace", fontWeight: 600 }}>
                KES {parseFloat(r.amount).toLocaleString()}
              </span>
            </div>
          ))}
          <div style={{ display: "flex", justifyContent: "space-between", marginTop: 10, paddingTop: 10, borderTop: `2px solid ${C.border}`, fontWeight: 700 }}>
            <span>Total</span>
            <span style={{ fontFamily: "'DM Mono', monospace", color: C.indigo }}>
              KES {group.rows.reduce((s, r) => s + parseFloat(r.amount || 0), 0).toLocaleString("en-KE")}
            </span>
          </div>
        </div>

        {status === "done"  && result   && <Alert type="success" msg={`✅ ${result.invoices_created || "All"} invoices created for ${group.class_name || `Class ${group.class_id}`}!`} />}
        {status === "error" && errorMsg && <Alert type="error"   msg={errorMsg} onDismiss={() => setStatus("idle")} />}

        <div style={{ display: "flex", gap: 10 }}>
          <Btn variant="outline" onClick={onClose} style={{ flex: 1 }}>Cancel</Btn>
          <Btn variant="outline" onClick={handlePrint} style={{ flex: 1 }}>🖨 Export PDF</Btn>
          <Btn
            loading={status === "loading"}
            disabled={status === "done"}
            style={{ flex: 2 }}
            onClick={handleGenerate}
          >
            {status === "done" ? "✅ Done" : " Generate Invoices"}
          </Btn>
        </div>
      </div>
    </Modal>
  );
};